Repository neuralmagic/deepsparse, pull requests merged in 2022-08, with the labels that each got.

#559 Update `deepsparse.server` to display task list programmatically
  src/deepsparse/server/main.py
Labels: enhancement

#560 Remove: `numpy.ndarray` from ImageClassification schema
  src/deepsparse/image_classification/schemas.py
Labels: bug

#567 Enabling hyphenated task names in deepsparse.server
  src/deepsparse/server/main.py
Labels: bug

#564 Remove: `numpy.ndarray` ImageClassification schema
  src/deepsparse/image_classification/schemas.py
Labels: bug

#562 Remove duplicate line 153
  src/deepsparse/pipeline.py
Labels: enhancement

#570 [cherry-pick] Enabling hypenated task names in deepsparse.server (#567)
  src/deepsparse/server/main.py
Labels: bug

#521 [BugFix] Server Computer Vision `from_file` fixes
  setup.py
  src/deepsparse/image_classification/README.md
  src/deepsparse/image_classification/schemas.py
  src/deepsparse/server/main.py
  src/deepsparse/server/utils.py
  src/deepsparse/yolact/pipelines.py
  src/deepsparse/yolact/schemas.py
  src/deepsparse/yolact/utils/annotate.py
  src/deepsparse/yolo/pipelines.py
  src/deepsparse/yolo/schemas.py
  tests/deepsparse/pipelines/test_schemas_from_files.py
Labels: bug

#607 Remove click versions from everywhere except `setup.py`
  examples/aws-sagemaker/requirements.txt
  examples/twitter-nlp/requirements.txt
  src/deepsparse/image_classification/__init__.py
Labels: dependencies
