Repository neuralmagic/deepsparse, pull requests merged in 2023-03, with the labels that each got.

#939 [BugFix] Add opencv to IC AutoInstalls
  src/deepsparse/image_classification/__init__.py
Labels: bug, mle-team

#948 [Cherry-pick] Update: YOLO pipeline to return scaled Boxes (#881)
  src/deepsparse/utils/annotate.py
  src/deepsparse/yolo/annotate.py
  src/deepsparse/yolo/pipelines.py
  src/deepsparse/yolo/utils/utils.py
Labels: mle-team

#934 Update Docker Infra
  .github/workflows/build-and-publish-tagged-images.yaml
  docker/Dockerfile
  docker/README.md
Labels: mle-team

#953 Migrate analyze functionality to `deepsparse.debug_analysis`
  setup.py
  src/deepsparse/debug_analysis.py
  src/deepsparse/engine.py
Labels: enhancement, mle-team

#970 `deepsparse.analyze`
  setup.py
  src/deepsparse/analyze.py
Labels: enhancement, mle-team
